### ISSUE TITLE
Boucle For

### ISSUE THREAD

**Issue by Zimmi48** [jorisgio/lics-compiler#8]
La boucle For doit être disponible à l'intérieur de la définition des portes. Cela pourrait être une macro qui copie simplement n fois, n étant une constante entière, la porte en lui donnant des noms numérotés.
Exemple de ce que ça pourrait donner :
Adder4bit<-inp
Adder1bit adder0 <-(inp.0,inp.1);
For i = 1 to 3
{ Adder1bit adder<i> <-(adder<i-1>.1,inp.<i+1>); }
For i = 0 to 3
{ outp.<i> = adder<i>.0; }
outp.4 = adder4.1;
->outp
qui donnerait après prétraitement :
Adder4bit<-inp;
Adder1bit adder0 <-(inp.0,inp.1);
Adder1bit adder1 <-(adder0.1,inp.2);
Adder1bit adder2 <-(adder1.1,inp.3);
Adder1bit adder3 <-(adder2.1,inp.4);
outp.0 = adder0.0;
outp.1 = adder1.0;
outp.2 = adder2.0;
outp.3 = adder3.0;
outp.4 = adder4.1;
->outp

ou bien, si on veux éviter le renommage tel que je le fais pour définir le tableau de sortie, on pourrait aussi remplacer la fin par

->(For i = 0 to 3 { adder<i>.0, } adder4.1)

L'avantage de cette méthode est, je crois, que le prétraitement peut se faire simplement avec un petit parser codé pour l'occasion.

**Comment by jorisgio** [comment]
oulah pourquoi compliquer le tout ? On peut simplement traiter le for pendant la construction du graphe, en ajoutant des noeuds. Je vois pas pourquoi faire une étape de plus.

**Comment by jorisgio** [comment]
:D
